// app
export const SET_THEME = 'SET_THEME';
export const SET_SUBTITLE = 'SET_SUBTITLE';
export const SET_ANIMATION_ENABLED = 'SET_ANIMATION_ENABLED';
export const SET_CURRENT_TOOLBAR = 'SET_CURRENT_TOOLBAR';
// users
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
// nodes
export const CREATE_MICRON = 'CREATE_MICRON';
export const UPDATE_MICRON = 'UPDATE_MICRON';
export const DELETE_MICRON = 'DELETE_MICRON';
export const SHOW_MICRON = 'SHOW_MICRON';
export const INDEX_MICRONS = 'INDEX_MICRONS';
export const ADD_MICRON_PROPERTY = 'ADD_MICRON_PROPERTY';
export const DELETE_MICRON_PROPERTIES = 'DELETE_MICRON_PROPERTIES';

export const INCREMENT_MICRONS_Y_ENDS = 'INCREMENT_MICRONS_Y_ENDS';
